### ISSUE TITLE
Resolve 0 STX pooling shown when pooling

### ISSUE THREAD

**Issue by SteliosSam** [hirosystems/desktop-wallet#1155]
![hiro](https://user-images.githubusercontent.com/118251422/214475001-18758181-4224-43e6-b5b2-b24cb68e140b.jpg)

Bug found testing Hiro Wallet build undefined, 4.8.0.

While i am pooling , i have locked, staked 310 STX, it shows i am pooling 0 STX in the stake right window. On the main screen it shows correctly 310 STX locked

**Comment by 314159265359879** [comment]
Hi @SteliosSam, thank you for reporting this. I believe this is a similar report to: https://github.com/hirosystems/stacks-wallet/issues/1150

I see the underlaying API issue has been resolved (https://github.com/hirosystems/stacks-blockchain-api/issues/1520) @edu-stx is anything else needed for the wallet to show the correct amount again?

Could it be that it is showing data from before the fix and it just hasn't connected with the fixed API yet?

Checking on a testnet wallet, at least it starts out correctly:
![image](https://user-images.githubusercontent.com/33360391/215194738-7f0d5cd1-da6f-40c4-baf6-34cec20dd469.png)

**Comment by edu-stx** [comment]
I'm not sure what's going on, still investigating, but the API seems to be reporting no balance. Did I miss something?

Request,

```
Request URL: https://stacks-node-api.testnet.stacks.co/v2/accounts/ST1DBN5D84A1DW6W69TN7Y6HZACG6PFTZ7QZYXD5M?proof=0
```

Response,

```json
{
    "balance":"0x00000000000000000000000000000000",
    "locked":"0x00000000000000000000000000000000",
    "unlock_height":0,
    "nonce":3
}
```

Although I was able to fix by using the accounts api.
