### ISSUE TITLE
Accept valid pool contract addresses for stacking

### ISSUE THREAD

**Issue by friedger** [hirosystems/desktop-wallet#1165]
When typing a valid smart contract address as pool address it is rejected as invalid:

![image](https://user-images.githubusercontent.com/1449049/226601471-44b61c95-f755-4fb2-bd5c-6a477ecb3bd5.png)

**Comment by friedger** [comment]
The current pool address for Fast Pool is SP21YTSM60CAY6D011EZVEVNKXVW8FVZE198XEFFP.pox-fast-pool-v1

**Comment by markmhx** [comment]
Any particular reason / advantage to using the contract here if we're not collecting BTC addresses?

**Comment by friedger** [comment]
@markmhx it is not about btc rewards but about the pool operator. That can be a stx address or a smart contract address. A principal.
