### ISSUE TITLE
[4.8.0] Bug: <Secret Keys causing BIP-39 non-compliance errors>

### ISSUE THREAD

**Issue by weitau** [hirosystems/desktop-wallet#1166]
Bug found testing Hiro Wallet build undefined, 4.8.0.

Hello, I am using a 24 word secret key phrase that has worked in the past with previous Hiro/Blockstack wallets.
Now it appears that my key phrase is not being accepted.

Email correspondence with werner.btc indicates another recent case where secret keys are failing validation, but the were still able to continue and access the wallet.

My secret key was taken from a 6x4 matrix via screen shot.  Naturally I am not able to share this key.
Please refer to werner.btc for additional details.

**Comment by 314159265359879** [comment]
Thanks for reporting. I will reply in the email. 

For reference the "failed validation" I referred to was only in the Wallet Extension and was a messaging error rather than failed validation.
