### ISSUE TITLE
[4.8.0] Bug: <describe issue>

### ISSUE THREAD

**Issue by henryaraya** [hirosystems/desktop-wallet#1167]
hello I am restoring my wallet and I  keep receiving the message Your Secret Key is not BIP-39 compliant.  I confirmed wit the list of words and all the words are in English and compliant according to https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

Thanks

Henry

  Thanks for creating an issue. Please include as much detail as possible,
  including screenshots, operating system, and steps to recreate the problem.

  If you have any questions, ask @kyranjamie or @aulneau on Github, Discord and Twitter.

-->

Bug found testing Hiro Wallet build undefined, 4.8.0.

**Comment by kyranjamie** [comment]
Even if all the words are in the list, if they're in the wrong order, it won't pass the checksum validation. The wallet would never have generated a non-compliant key.

**Comment by 314159265359879** [comment]
This has been resolved in a call. The word order was misinterpreted.

**Comment by 314159265359879** [comment]
I think maybe this is a similar but different issue, please contact me if it persists wallet at hiro dot so

**Comment by henryaraya** [comment]
Thanks. Resolved one word misspelled was the problem I did group the words in columns of three words. Also i double checked with the site https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt what was very useful.
