### ISSUE TITLE
[4.8.0] Bug: <Trying to move STX from Hiro wallet and it gives me an "unable to decrypt" message - occurred in previous version as well

### ISSUE THREAD

**Issue by haparnold** [hirosystems/desktop-wallet#1171]
Bug found testing Hiro Wallet build undefined, 4.8.0.

**Comment by haparnold** [comment]
Got an "unable to decrypt wallet" message while trying to move STX from wallet - please advise

**Comment by lp662lp662** [comment]
Shit up

haparnold ***@***.***>於 2023年3月30日 週四，上午4:34寫道：

**Comment by markmhx** [comment]
Was this with Ledger or software mode / entering a Secret Key directly?

**Comment by haparnold** [comment]
It was after entering the password.  I tried the Chrome extension and had no trouble accomplishing what I needed to. Thank you
