### ISSUE TITLE
Fix display of pending transactions in activity

### ISSUE THREAD

**Issue by markmhx** [hirosystems/desktop-wallet#1173]
They seem not to appear while pending, either for delegation transactions or regular STX sends:

## First

<img width="783" alt="Screenshot 2023-03-30 at 09 36 27" src="https://user-images.githubusercontent.com/28991/228764286-98a102ff-e937-435b-ba0c-658c31de61da.png">
<img width="914" alt="Screenshot 2023-03-30 at 09 28 17" src="https://user-images.githubusercontent.com/28991/228764295-9927c06b-6243-4343-b34b-5d08e39a15e9.png">

## Then

<img width="799" alt="Screenshot 2023-03-30 at 09 48 49" src="https://user-images.githubusercontent.com/28991/228767217-aa604094-8be4-4de2-8825-6f0b3158d219.png">
<img width="906" alt="Screenshot 2023-03-30 at 09 48 45" src="https://user-images.githubusercontent.com/28991/228767222-be01b277-df38-4060-a0bf-56f4a455b22a.png">

**Comment by 314159265359879** [comment]
@markmhx as Hero-Gamer pointed out in #1161 _otherwise the user might attempt again creating unnecessary duplicate tx._ we have definitely been seeing that. 
Perhaps a good reason to handle this as a P2 because it adds additional issues when users do not realize prior transactions are successfully transmitted.

**Comment by markmhx** [comment]
@kyranjamie reminder about this one while you're in the desktop code 🙏

**Comment by kyranjamie** [comment]
@markmhx @314159265359879 Are we sure this is a problem still?

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/1618764/232465297-4fdd6922-8a80-4fe0-8c8c-3077493287e0.png">

It could've been that there were a temp issue with the mempool?

**Comment by markmhx** [comment]
Mind sending a transaction on mainnet to test / confirm? If you need me to, I can also QA it again.

**Comment by kyranjamie** [comment]
This also worked too

<img width="784" alt="image" src="https://user-images.githubusercontent.com/1618764/232479592-475ead67-9c77-494d-9dfa-810df0b67686.png">
