### ISSUE TITLE
Interference of active Hiro Wallet with Google Docs

### ISSUE THREAD

**Issue by paradigma-cl** [hirosystems/desktop-wallet#1177]
In google chrome when the Hiro Wallet is active, Google docs in the same browse fails to load a document.
![WhatsApp Image 2023-03-30 at 16 02 34](https://user-images.githubusercontent.com/32182666/228949577-d76d7b8c-1064-4b34-907d-25eb0f100006.jpeg)
When the Hiro Wallet is not active, there are not issues to load a document into Google docs.
Then the Hiro Wallet is put Active, and the icon gets displayed.
![WhatsApp Image 2023-03-30 at 16 04 22](https://user-images.githubusercontent.com/32182666/228949591-a6ba422d-9cfd-4ec2-b00a-1a6a9dbf0e0c.jpeg)
Then the google docs cannot load a document.
![WhatsApp Image 2023-03-30 at 16 05 36](https://user-images.githubusercontent.com/32182666/228949603-155a62d1-b013-4373-aa6a-e25ff3ded6e1.jpeg)
We are worried that new users can have problems when using Google docs in the same browser with the Hiro Wallet.

**Comment by 314159265359879** [comment]
Thanks for reporting. We have an issue for this in the web wallet repo: https://github.com/hirosystems/wallet/issues/3502 it is being investigated. 
The workaround seems to work: uninstalling the extension and then installing it again.
