### ISSUE TITLE
[4.6.1] Bug: <describe issue>

### ISSUE THREAD

**Issue by grainear** [hirosystems/desktop-wallet#1179]
tryng to transfer STX tokens from Hiro Wallet to KuCoin exchange   Perhaps I need to upgrade Hiro ?

Bug found testing Hiro Wallet build undefined, 4.6.1.

**Comment by 314159265359879** [comment]
Please update to the latest version of the wallet. Also allow some time for the transfer to get confirmed average confirmation time is 10 minutes but 2-60 minutes does happen too.
