### ISSUE TITLE
[4.9.0-dev.1] Bug: <describe issue>

### ISSUE THREAD

**Issue by TC-ux** [hirosystems/desktop-wallet#1183]
Bug found testing Hiro Wallet build undefined, 4.9.0-dev.1.

Hello, I've downloaded last hiro wallet desktop version (MacOS 11.7) and was trying to stake my STX using this pool address SP21YTSM60CAY6D011EZVEVNKXVW8FVZE198XEFFP.pox-fast-pool-v1
I got from this webpage : https://pool.friedger.de/

Unfortunately, each time try (after entering the address, selecting the number of STX I want to stake, and choosing infinite mode) the Hiro wallet turns to black when I press the "confirm and start pooling" button  (no more writing). Even if I wait, nothing happens. When relaunching the hiro wallet, I can fin back my STX but pooling hasn't work. 

Warm regards
Tristan

**Comment by 314159265359879** [comment]
Hi Tristan, thanks for reporting. Likely due to this https://github.com/hirosystems/desktop-wallet/issues/1182

**Comment by TC-ux** [comment]
Hi, thank you for your answer, If I understand correctly, I have to use the 6.5.0 wallet version ? The thing is I've tried a 6+ version before, but it couldn't recognize the address I showed you, furthermore on the web page I showed you (https://pool.friedger.de/) it's written to use the last version 4.9. Hence my dowloading of the last version.

**Comment by 314159265359879** [comment]
@TC-ux Sorry for the confusing link, no the solution described there is something the devs have to update (6.5.0 is referring to a software package). 
The 4.8.0 version is indeed not compatible with the Friedger pool contract. The alternative that does work would be to install the Hiro Wallet extension for (Brave, Chrome or Firefox) and then use that to connect with the lockstacks.com dapp, that will allow delegating to the pooling contract.

**Comment by 314159265359879** [comment]
You would get access to your funds on the Desktop Wallet by using the same Secret Key for the extension. The wallets just provide access to your on chain assets.

**Comment by TC-ux** [comment]
Sure, will try it, thank you very much
