### ISSUE TITLE
Mitigate against memo abuse (e.g. scam messages)

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/desktop-wallet#1192]
If you see something like this in your wallet, ignore it. the website is phishing for your keys. 

![image](https://user-images.githubusercontent.com/33360391/236486987-108fa060-6170-4f22-910b-963c5dc71305.png)

Some options to deal with this in the wallet:
1. Show a partial memo
2. filter out urls
3. filter out common scam messages
4. flag anything that is not a random string of characters (commonly used for memo's on exchanges) or yes/no/agree/disagree (commonly used for voting)
5. Do not show memo until we have a better solution.

Or perhaps
6. Leave it as is and expect users to use common sense.

**Comment by markmhx** [comment]
either 2 or 5 sound fine to me

**Comment by 314159265359879** [comment]
I am in favour of 5, it is in line with the web extension and it also prevents a phisher to work around 2.

**Comment by kyranjamie** [comment]
5*: don't show memos _on inbound transactions_

**Comment by markmhx** [comment]
@friedger is this something you could tackle this week or prefer someone else does? 🙏
