### ISSUE TITLE
[4.9.1] Bug: Your Secret Key is not BIP-39 compliant.

### ISSUE THREAD

**Issue by fire717** [hirosystems/desktop-wallet#1199]
Bug found testing Hiro Wallet build undefined, 4.9.1.

I write my secret key in my notebook, and today I wanna log in hiro wallet, I found that I need to recover it, so I type my 24 words, however it says: Your Secret Key is not BIP-39 compliant.

I have ctrl+f to find every word is in the words list, so what's wrong?

**Comment by fire717** [comment]
And I write down the words in one line, so it may not the order problem.

**Comment by markmhx** [comment]
Please contact our support team at wallet@hiro.so to diagnose the issue!
