### ISSUE TITLE
[4.10.0] Bug: Incorrect Locked STX amount and available balance

### ISSUE THREAD

**Issue by stefanostatuti** [hirosystems/desktop-wallet#1202]
Hello, there is a small difference between total stx and stacked stx (110 vs 111, remaining stx are bugged too).
Tx on chain confirms the correct amount `https://explorer.hiro.so/txid/0x3c65142cc73d3b6ccbf168a23e62024847e15ceed7b9f4261cceef0d2a1ad026?chain=mainnet`

Bug found testing Hiro Wallet build undefined, 4.10.0.

![bug](https://github.com/hirosystems/desktop-wallet/assets/4499372/f39c3376-c76f-4334-abc5-bc79f9c1ef1d)

**Comment by 314159265359879** [comment]
@stefanostatuti Did you lock with Friedger pool?

Friedgerpool will always leave 1 STX so you can cover fees for other transactions and to (one day) revoke the delegation if you ever want to do that.

**Comment by stefanostatuti** [comment]
hello, yes i used Friedger pool. so this is normal the difference?

**Comment by friedger** [comment]
The pooled amount is the maximum that a pool can lock for you. It can be much higher than your actual stx balance.
The locked amount is the amount that the pool admin did stack for you. 
Currently, the buffer is set to 1stx.
