### ISSUE TITLE
Second step of delegating fails to broadcast

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/desktop-wallet#1203]
_Hey there! posting here also : since update 4.10 of desktop Hiro Wallet, when i try to delegate to stack, it seems Hiro Wallet doesn't send a "sign transaction" message to my Ledger S, so I can't delegate; any infos on this ?_

![image](https://github.com/hirosystems/desktop-wallet/assets/33360391/11cbad5b-ced0-4d5d-ba41-912289146a63)

For the Ledger user this has persisted for more than a day. 

A similar issue was reported with the Desktop wallet in software-key-mode and the user reported it resolved a day later. 

I have been unable to reproduce this.

**Comment by markmhx** [comment]
@friedger can you take this soon or prefer someone else do?

**Comment by friedger** [comment]
@markmhx It is not reproducable. I suggest to close for now. User reported back that it works for them now.
