### ISSUE TITLE
[4.9.1] Bug: black out on stacking flow

### ISSUE THREAD

**Issue by croing** [hirosystems/desktop-wallet#1205]
Bug found testing Hiro Wallet build undefined, 4.9.1.

Hi
The Hiro wallet turned to be back out when I tried to stake. Even aborted it during the staking. The app charged the fee again.

**Comment by 314159265359879** [comment]
Please make sure to use the latest version of the wallet 4.10.0 is compatible with the latest proof of transfer (PoX-3) contract. If the issue does persist please add a screenshot of the error.

**Comment by friedger** [comment]
New version released
