### ISSUE TITLE
Show amount on Ledger device while confirming Stacking delegation transaction

### ISSUE THREAD

**Issue by markmhx** [hirosystems/desktop-wallet#875]
The Stacks Wallet should cause the user's Ledger device to show the amount of STX they will be delegating for Stacking when confirming the transaction on their device.

[See related Stacks app for Ledger issue in Zondax repository](https://github.com/Zondax/ledger-blockstack/issues/67)

Ledger is reporting that they need this enhancement in order to approve the Stacks app for removal of "developer mode".

**Comment by markmhx** [comment]
Assigning to @kyranjamie to help move this forward once we chat with @jleni Zondax tomorrow.

**Comment by markmhx** [comment]
@kyranjamie to provide guidance to @jleni on how parameters are passed as a hash to the Ledger app.

**Comment by kyranjamie** [comment]
Detailed on @zondax's repo https://github.com/Zondax/ledger-blockstack/issues/67#issuecomment-892641467

**Comment by markmhx** [comment]
A fix is ready with https://github.com/Zondax/ledger-blockstack/releases/tag/v0.14.0

We should QA on our end then notify Ledger.

**Comment by markmhx** [comment]
@kyranjamie let's QA this now that we've released for fee adjustments?

**Comment by kyranjamie** [comment]
Yes, let's.

**Comment by timstackblock** [comment]
The ledger is frozen in the screen below pressing any combination of buttons does nothing. I will move this issue back to in dev.

![20210913_100444](https://user-images.githubusercontent.com/49165468/133098694-22afffe7-f99a-4144-8038-e5b8e3dcf53e.jpg)

**Comment by timstackblock** [comment]
The freezing error is resolved just waiting for my STX to clear on okcoin to retest.

**Comment by timstackblock** [comment]
Test passed :shipit:
